# SVOX Pico via ../pico-say; $VOICE is Pico's language code
GenericExecuteSynth \
"printf %s \'$DATA\' | $HOME/.config/speech-dispatcher/pico-say $VOICE $RATE"
AddVoice "en-GB" "FEMALE1" "en-GB"
AddVoice "en-US" "FEMALE1" "en-US"
DefaultVoice "en-GB"
