 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Florence Config", "florence --config", "///usr/share/pixmaps/florence.svg" },
     {"Florence Virtual Keyboard", "florence", "///usr/share/pixmaps/florence.svg" },
     {"Jovie", "jovie"},
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"Kvkbd", "kvkbd", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/gnome/16x16/actions/gtk-find.png" },
     {"Ark", "ark -caption Ark ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Artha", "artha", "/usr/share/pixmaps/artha.png" },
     {"Calise", "calise", "/usr/share/icons/hicolor/16x16/apps/calise.png" },
     {"Catfish File Search", "catfish", "/usr/share/pixmaps/catfish.svg" },
     {"Disks", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Florence Config", "florence --config", "///usr/share/pixmaps/florence.svg" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"Jovie", "jovie"},
     {"KCalc", "kcalc -caption KCalc", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KCharSelect", "kcharselect -caption KCharSelect", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"KRename", "krename -caption \"KRename\"   ", "/usr/share/icons/hicolor/32x32/apps/krename.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kvkbd", "kvkbd", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard.png" },
     {"Launchy", "launchy ", "/usr/share/pixmaps/launchy_icon.png" },
     {"PDF Editor", "pdfedit", "/usr/share/pixmaps/pdfedit.png" },
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"Recoll", "recoll", "/usr/share/icons/hicolor/48x48/apps/recoll.png" },
     {"Redshift", "redshift-gtk"},
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"SpaceFM File Search", "spacefm --find-files ", "/usr/share/icons/hicolor/48x48/apps/spacefm-find.png" },
     {"Sweeper", "sweeper"},
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Xfi", "xfi", "/usr/share/pixmaps/xfi.png" },
     {"Xfp", "xfp", "/usr/share/pixmaps/xfp.png" },
     {"Xfv", "xfv", "/usr/share/pixmaps/xfv.png" },
     {"Xfw", "xfw", "/usr/share/pixmaps/xfw.png" },
     {"Xgnokii", "xgnokii", "/usr/share/icons/gnome/16x16/devices/phone.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"pyRenamer", "/usr/bin/pyrenamer", "///usr/share/pyrenamer/pyrenamer.png" },
     {"qtFM", "qtfm", "/usr/share/pixmaps/qtfm.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Marble", "marble ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Mendeley Desktop", "mendeleydesktop", "/usr/share/icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"Stellarium nightsky renderer", "stellarium", "/usr/share/icons/hicolor/16x16/apps/stellarium.png" },
     {"lxnstack", "lxnstack", "/usr/share/icons/lxnstack.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"AcquireImages", "scangui  -caption AcquireImages ", "/usr/share/icons/gnome/16x16/devices/scanner.png" },
     {"Briss", "briss", "///usr/share/briss/briss-icon.png" },
     {"DNGConverter", "dngconverter  -caption DNGConverter ", "/usr/share/icons/hicolor/16x16/apps/kipi-dngconverter.png" },
     {"Darktable", "darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"ExpoBlending", "expoblending  -caption ExpoBlending ", "/usr/share/icons/hicolor/16x16/apps/kipi-expoblending.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"ImageViewer", "imageviewer", "/usr/share/pixmaps/imageviewer.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"KGraphEditor", "kgrapheditor ", "/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"KGraphViewer", "kgraphviewer  -caption KGraphViewer", "/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Panorama", "panoramagui  -caption Panorama ", "/usr/share/icons/hicolor/16x16/apps/kipi-panorama.png" },
     {"Photo Layouts Editor", "photolayoutseditor", "/usr/share/icons/hicolor/16x16/apps/photolayoutseditor.png" },
     {"RawTherapee", "rawtherapee ", "/usr/share/icons/hicolor/16x16/apps/rawtherapee.png" },
     {"UFRaw", "ufraw ", "/usr/share/pixmaps/ufraw.png" },
     {"digiKam", "digikam -caption digiKam ", "/usr/share/icons/hicolor/16x16/apps/digikam.png" },
     {"lxnstack", "lxnstack", "/usr/share/icons/lxnstack.png" },
     {"showFoto", "showfoto  -caption showFoto ", "/usr/share/icons/hicolor/16x16/apps/showfoto.png" },
     {"yEd Graph Editor", "yed ", "/usr/share/pixmaps/yed.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Deluge", "deluge-gtk ", "/usr/share/icons/hicolor/16x16/apps/deluge.png" },
     {"GNUnet Secured P2P", "gnunet-fs-gtk", "/usr/share/icons/hicolor/16x16/apps/gnunet-fs-gtk.png" },
     {"GNUnet Setup", "gnunet-setup"},
     {"GmoteServer", "/opt/gmote/GmoteServer.sh", "///opt/gmote/gmote.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"KTorrent", "ktorrent ", "/usr/share/icons/hicolor/16x16/apps/ktorrent.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Opera", "/usr/bin/opera ", "/usr/share/icons/hicolor/16x16/apps/opera-browser.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"QupZilla", "qupzilla ", "/usr/share/icons/hicolor/16x16/apps/qupzilla.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Trojitá", "trojita", "/usr/share/icons/hicolor/32x32/apps/trojita.png" },
     {"Vidalia", "vidalia", "/usr/share/icons/hicolor/16x16/apps/vidalia.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/icons/hicolor/16x16/apps/wicd-gtk.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calligra Author", "calligraauthor ", "/usr/share/icons/hicolor/16x16/apps/calligraauthor.png" },
     {"Calligra Flow", "calligraflow ", "/usr/share/icons/hicolor/16x16/apps/calligraflow.png" },
     {"Calligra Sheets", "calligrasheets ", "/usr/share/icons/hicolor/16x16/apps/calligrasheets.png" },
     {"Calligra Stage", "calligrastage ", "/usr/share/icons/hicolor/16x16/apps/calligrastage.png" },
     {"Calligra Words", "calligrawords ", "/usr/share/icons/hicolor/16x16/apps/calligrawords.png" },
     {"Gnumeric", "gnumeric ", "/usr/share/icons/hicolor/16x16/apps/gnumeric.png" },
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"Kile", "kile ", "/usr/share/icons/hicolor/16x16/apps/kile.png" },
     {"LyX Document Processor", "lyx ", "/usr/share/pixmaps/lyx.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Pybliographic Bibliography Manager", "pybliographic", "/usr/share/pixmaps/pybliographic.png" },
     {"TeXworks", "texworks ", "/usr/share/pixmaps/TeXworks.png" },
     {"Trojitá", "trojita", "/usr/share/icons/hicolor/32x32/apps/trojita.png" },
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"Xgnokii", "xgnokii", "/usr/share/icons/gnome/16x16/devices/phone.png" },
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.xpm" },
     {"YAGF", "yagf ", "/usr/share/pixmaps/yagf.png" },
     {"llpp", "llpp "},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Code::Blocks IDE", "codeblocks ", "/usr/share/pixmaps/codeblocks.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Eric 5", "eric5", "/usr/share/pixmaps/eric.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"GATE", "gate", "/usr/share/pixmaps/gate.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"KDiff3", "kdiff3  -caption \"KDiff3\"", "/usr/share/icons/hicolor/16x16/apps/kdiff3.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"PythonToolkit (PTK)", "PTK -f ", "/usr/share/pixmaps/ptkicon.svg" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "/usr/bin/qtcreator", "///usr/share/icons/hicolor/512x512/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"SciTE Text Editor", "SciTE ", "/usr/share/pixmaps/Sci48M.png" },
     {"TortoiseHg", "thg --nofork", "/usr/share/pixmaps/thg_logo.svg" },
     {"Weka", "/usr/bin/weka", "/usr/share/pixmaps/weka.png" },
     {"Winpdb", "winpdb", "///usr/share/icons/winpdb-icon-16.png" },
     {"XDot", "python2 /home/shared/Source/xdot-git/xdot.py"},
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"kdesvn", "kdesvn -caption \"kdesvn\"", "/usr/share/icons/hicolor/16x16/apps/kdesvn.png" },
     {"textadept", "textadept"},
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Gnumeric", "gnumeric ", "/usr/share/icons/hicolor/16x16/apps/gnumeric.png" },
     {"Weka", "/usr/bin/weka", "/usr/share/pixmaps/weka.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Audio Mixer", "xfce4-mixer", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Avidemux (GTK+)", "avidemux2_gtk", "/usr/share/pixmaps/avidemux.png" },
     {"Ex Falso", "exfalso", "/usr/share/icons/hicolor/64x64/apps/exfalso.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"GTK sound mixer", "/usr/bin/aumix", "///usr/share/aumix/aumix.xpm" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"Guitune", "gtkguitune"},
     {"HandBrake", "ghb", "/usr/share/icons/hicolor/16x16/apps/hb-icon.png" },
     {"Kdenlive", "kdenlive  -caption \"Kdenlive\" ", "/usr/share/icons/hicolor/32x32/apps/kdenlive.png" },
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QjackCtl", "/usr/bin/qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"Qsynth", "/usr/bin/qsynth", "/usr/share/icons/hicolor/32x32/apps/qsynth.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qtractor", "/usr/bin/qtractor", "/usr/share/icons/hicolor/32x32/apps/qtractor.png" },
     {"Quod Libet", "quodlibet", "/usr/share/icons/hicolor/64x64/apps/quodlibet.png" },
     {"Rosegarden", "rosegarden ", "/usr/share/icons/hicolor/32x32/apps/rosegarden.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"SMPlayer YouTube Browser", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"soundKonverter", "soundkonverter ", "/usr/share/icons/hicolor/16x16/apps/soundkonverter.png" },
     {"tuxguitar", "tuxguitar  -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Andromeda", "andromeda", "/usr/share/pixmaps/andromeda.png" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Cairo-Dock", "cairo-dock", "/usr/share/pixmaps/cairo-dock.svg" },
     {"Cairo-Dock (Fallback Mode)", "cairo-dock -A", "/usr/share/pixmaps/cairo-dock.svg" },
     {"Configuration Editor", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Dolphin", "dolphin  -caption Dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"PkgBrowser", "pkgbrowser", "/usr/share/icons/hicolor/48x48/apps/pkgbrowser.png" },
     {"Searchmonkey", "searchmonkey"},
     {"Sensor Viewer", "xfce4-sensors", "/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"SpaceFM", "spacefm ", "/usr/share/icons/hicolor/48x48/apps/spacefm.png" },
     {"System Profiler and Benchmark", "hardinfo", "///usr/share/hardinfo/pixmaps/logo.png" },
     {"Task Manager", "lxtask", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfe", "xfe", "/usr/share/pixmaps/xfe.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"gtk2fontsel", "gtk2fontsel"},
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

