 menu78059f1898ed518c6ccd6a6392fa82c1 = {     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share//icons/hicolor/32x32/apps/arch-logo.png" },
 }

 menu330f49df8243756a8a4dc7f7f7ee6dfe = {     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Code::Blocks IDE", "codeblocks ", "/usr/share/pixmaps/codeblocks.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"Eclipse", "eclipse", "/usr/share//icons/hicolor/32x32/apps/eclipse.png" },
     {"Emacs", "emacs ", "/usr/share//icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share//icons/hicolor/16x16/apps/fluid.png" },
     {"GHex", "ghex ", "/usr/share//icons/hicolor/16x16/apps/ghex.png" },
     {"Geany", "geany ", "/usr/share//icons/hicolor/16x16/apps/geany.png" },
     {"Glade", "glade ", "/usr/share//icons/hicolor/16x16/apps/glade.png" },
     {"KDiff3", "kdiff3  -caption \"KDiff3\"", "/usr/share//icons/hicolor/16x16/apps/kdiff3.png" },
     {"Meld", "meld ", "/usr/share//icons/hicolor/16x16/apps/meld.png" },
     {"Nemiver", "nemiver", "/usr/share//icons/hicolor/16x16/apps/nemiver.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/lib/jvm/java-6-openjdk/bin/jconsole", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/lib/jvm/java-6-openjdk/bin/policytool", "/usr/share//icons/hicolor/16x16/apps/java.png" },
     {"PythonToolkit (PTK)", "PTK -f ", "/usr/share/pixmaps/ptkicon.svg" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt Assistant", "/usr/bin/assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/bin/designer", "/usr/share//icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/bin/linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
     {"Redstart", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/redstart ", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"SciTE Text Editor", "SciTE ", "/usr/share/pixmaps/Sci48M.png" },
     {"Spyder", "spyder"},
     {"Tortoise HG", "thg"},
     {"Voice Import Tools", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/voiceimport ", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"Winpdb", "winpdb", "///usr/share/icons/winpdb-icon-16.png" },
     {"eric5", "eric5", "/usr/share/pixmaps/eric.png" },
     {"kdesvn", "kdesvn -caption \"kdesvn\"", "/usr/share//icons/hicolor/16x16/apps/kdesvn.png" },
 }

  menu387baf0199e7c9cc944fae94e96448fa = {      {"Brain Workshop", "brainworkshop", "/usr/share/pixmaps/brainworkshop.png" },
      {"Marble", "marble", "/usr/share//icons/hicolor/16x16/apps/marble.png" },
  }

 menude7a22a0c94aa64ba2449e520aa20c99 = {    {"Miscellaneous", menu387baf0199e7c9cc944fae94e96448fa},
 }

 menu251bd8143891238ecedc306508e29017 = {     {"Steam", "/usr/bin/steam ", "/usr/share//icons/hicolor/16x16/apps/steam.png" },
     {"Team Fortress 2 Beta", "steam steam://rungameid/520", "/usr/share//icons/hicolor/16x16/apps/steam.png" },
 }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {     {"AcquireImages", "scangui  -caption \"AcquireImages\" ", "/usr/share//icons/gnome/16x16/devices/scanner.png" },
     {"Briss", "briss", "///usr/share/briss/briss-icon.png" },
     {"DNGConverter", "dngconverter  -caption \"DNGConverter\" ", "/usr/share//icons/hicolor/16x16/apps/dngconverter.png" },
     {"Darktable", "darktable ", "/usr/share//icons/hicolor/16x16/apps/darktable.png" },
     {"ExpoBlending", "expoblending  -caption \"ExpoBlending\" ", "/usr/share//icons/hicolor/16x16/actions/expoblending.png" },
     {"Font Manager", "font-manager", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"Fontmatrix", "fontmatrix", "/usr/share//icons/hicolor/48x48/apps/fontmatrix.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Inkscape", "inkscape ", "/usr/share//icons/hicolor/16x16/apps/inkscape.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share//icons/hicolor/16x16/apps/kolourpaint.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MuPDF", "mupdf ", "/usr/share/pixmaps/mupdf.xpm" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"Panorama", "panoramagui  -caption \"Panorama\" "},
     {"Photo Layouts Editor", "photolayoutseditor", "/usr/share//icons/hicolor/16x16/apps/photolayoutseditor.png" },
     {"RawTherapee", "rawtherapee ", "/usr/share//icons/hicolor/16x16/apps/rawtherapee.png" },
     {"Shotwell", "shotwell ", "/usr/share//icons/hicolor/16x16/apps/shotwell.svg" },
     {"UFRaw", "ufraw ", "/usr/share/pixmaps/ufraw.png" },
     {"XnView Multi Platform", "xnviewmp", "///opt/xnviewmp/xnview.png" },
     {"digiKam", "digikam -caption \"digiKam\" ", "/usr/share//icons/hicolor/16x16/apps/digikam.png" },
     {"kgrapheditor", "kgrapheditor ", "/usr/share//icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"kgraphviewer", "kgraphviewer  -caption \"kgraphviewer\"", "/usr/share//icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"showFoto", "showfoto  -caption \"showFoto\" ", "/usr/share//icons/hicolor/16x16/apps/showfoto.png" },
     {"yEd Graph Editor", "yed ", "/usr/share/pixmaps/yed.png" },
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share//icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"FatRat", "fatrat", "/usr/share/pixmaps/fatrat.png" },
     {"Firefox", "firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager", "/usr/share//icons/hicolor/16x16/apps/google-musicmanager.png" },
     {"KTorrent", "ktorrent -caption \"KTorrent\" ", "/usr/share//icons/hicolor/16x16/apps/ktorrent.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share//icons/hicolor/16x16/apps/konqueror.png" },
     {"Midori", "midori ", "/usr/share//icons/hicolor/16x16/apps/midori.png" },
     {"Midori Private Browsing", "midori --private ", "/usr/share//icons/hicolor/16x16/apps/midori.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share//icons/hicolor/16x16/apps/pidgin.png" },
     {"Skype", "skype ", "/usr/share//icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share//icons/hicolor/16x16/apps/steam.png" },
     {"Vidalia", "vidalia", "/usr/share//icons/hicolor/16x16/apps/vidalia.png" },
     {"WiFi Radar", "gksudo -S wifi-radar", "/usr/share/pixmaps/wifi-radar.svg" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share//icons/hicolor/16x16/apps/wicd-gtk.png" },
 }

 menu1c1ecba6ad0b80ad52f0a2c15c785259 = {     {"Chrome", "/usr/bin/google-chrome", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"EmoSpeak", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/emospeak", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY Component Installer", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/mary-component-installer", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY HTTP documentation", "", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY Uninstaller", "/usr/lib/jvm/java-7-openjdk/jre/bin/java -jar \"/home/prash/Documents/CoLi/Resources/MARY/Uninstaller/uninstaller.jar\"", "/usr/share//icons/gnome/16x16/status/trashcan_full.png" },
     {"MARY client", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/maryclient", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY server", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/maryserver", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY web interface", "", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"XDot", "python2 /home/prash/src/xdot-git/xdot.py"},
     {"i3", "i3"},
 }

 menu2f56b4f336dc97edf739bf79523fb9a6 = {     {"Audacity", "audacity ", "/usr/share//icons/hicolor/16x16/apps/audacity.png" },
     {"Audio Mixer", "xfce4-mixer", "/usr/share//icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Avidemux (GTK+)", "avidemux2_gtk", "/usr/share/pixmaps/avidemux.png" },
     {"Clementine", "clementine ", "/usr/share//icons/hicolor/64x64/apps/application-x-clementine.png" },
     {"Ex Falso", "exfalso", "/usr/share//icons/hicolor/64x64/apps/exfalso.png" },
     {"FMIT", "fmit"},
     {"GTK sound mixer", "/usr/bin/aumix", "///usr/share/aumix/aumix.xpm" },
     {"Gnome Music Player Client", "gmpc", "/usr/share//icons/hicolor/16x16/apps/gmpc.png" },
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager", "/usr/share//icons/hicolor/16x16/apps/google-musicmanager.png" },
     {"Guitune", "gtkguitune"},
     {"HandBrake", "ghb", "/usr/share//icons/hicolor/128x128/apps/hb-icon.png" },
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk", "/usr/share//icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share//icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"QjackCtl", "/usr/bin/qjackctl", "/usr/share//icons/hicolor/32x32/apps/qjackctl.png" },
     {"Qsynth", "/usr/bin/qsynth", "/usr/share//icons/hicolor/32x32/apps/qsynth.png" },
     {"Quod Libet", "quodlibet", "/usr/share//icons/hicolor/64x64/apps/quodlibet.png" },
     {"Rosegarden", "rosegarden ", "/usr/share//icons/hicolor/32x32/apps/rosegarden.png" },
     {"SMPlayer", "smplayer ", "/usr/share//icons/hicolor/16x16/apps/smplayer.png" },
     {"Spotify", "spotify ", "/usr/share/pixmaps/spotify-linux-512x512.png" },
     {"VLC media player", "/usr/bin/vlc ", "/usr/share//icons/hicolor/16x16/apps/vlc.png" },
     {"soundKonverter", "soundkonverter  -caption \"soundKonverter\"", "/usr/share//icons/hicolor/16x16/apps/soundkonverter.png" },
     {"tuxguitar", "tuxguitar ", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"Adobe Reader 9", "acroread ", "/usr/share/pixmaps/acroread.png" },
     {"Kile", "kile ", "/usr/share//icons/hicolor/16x16/apps/kile.png" },
     {"LibreOffice ", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"LyX Document Processor", "lyx ", "/usr/share/pixmaps/lyx.png" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"Pybliographic Bibliography Manager", "pybliographic", "/usr/share/pixmaps/pybliographic.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"Wordview Microsoft doc Viewer", "wordview", "/usr/share/pixmaps/wordview.xpm" },
     {"Xpdf", "xpdf", "/usr/share/pixmaps/xpdf.xpm" },
 }

 menu80d754c83abbbd4ef5d150904efcc86c = {     {"Spyder", "spyder"},
 }

 menuf4f70727dc34561dfde1a3c529b6205c = {     {"Adobe Flash Player", "flash-player-properties", "/usr/share//icons/hicolor/16x16/apps/flash-player-properties.png" },
     {"Customize Look and Feel", "lxappearance", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Desktop Preferences", "pcmanfm --desktop-pref", "/usr/share//icons/gnome/16x16/places/user-desktop.png" },
     {"File Manager", "thunar-settings", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"IcedTea Web Control Panel", "/usr/lib/jvm/java-6-openjdk/bin/itweb-settings", "/usr/share/pixmaps/javaws.png" },
     {"KDE System Settings", "systemsettings -caption \"KDE System Settings\" ", "/usr/share//icons/gnome/16x16/categories/preferences-system.png" },
     {"Network Connections", "nm-connection-editor", "/usr/share//icons/gnome/16x16/categories/preferences-system-network.png" },
     {"Onboard Settings", "onboard-settings"},
     {"Openbox Configuration Manager", "obconf ", "/usr/share/pixmaps/obconf.png" },
     {"Panel tint2", "tint2conf", "/usr/share/pixmaps/tint2conf.png" },
     {"Preferred Applications", "libfm-pref-apps", "/usr/share//icons/gnome/16x16/categories/preferences-desktop.png" },
     {"PulseAudio Preferences", "paprefs", "/usr/share//icons/gnome/16x16/categories/preferences-desktop.png" },
     {"Removable Drives and Media", "thunar-volman-settings", "/usr/share//icons/gnome/16x16/devices/drive-removable-media.png" },
     {"Screensaver", "xscreensaver-demo", "/usr/share//icons/gnome/16x16/apps/xscreensaver.png" },
     {"TintWizard", "tintwizard ", "/usr/share/pixmaps/tint2conf.png" },
 }

 menua45da96d0bf6575970f2d27af22be28a = {     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share//icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Dolphin", "dolphin  -caption \"Dolphin\" ", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"GParted", "gparted-pkexec", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption \"KSystemLog\""},
     {"KUser", "xdg_menu_su kuser  -caption \"KUser\"", "/usr/share//icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share//icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share//icons/hicolor/16x16/apps/cups.png" },
     {"Manage Printing", "gtklp", "/usr/share//icons/gnome/16x16/devices/printer.png" },
     {"Manage Printing Queue", "gtklpq", "/usr/share//icons/gnome/16x16/devices/printer.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk File Indexing Controller", "nepomukcontroller"},
     {"PkgBrowser", "pkgbrowser", "/usr/share//icons/hicolor/48x48/apps/pkgbrowser.png" },
     {"Sensor Viewer", "xfce4-sensors", "/usr/share//icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"System Monitor", "ksysguard ", "/usr/share//icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Thunar File Manager", "thunar ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf Editor", "dconf-editor", "/usr/share//icons/hicolor/32x32/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share//icons/gnome/16x16/apps/terminal.png" },
 }

 menuceba282b7418b7f199798b645e1cba56 = {     {"Akonaditray", "akonaditray"},
     {"Application Finder", "xfce4-appfinder", "/usr/share//icons/gnome/16x16/actions/gtk-find.png" },
     {"Ark", "ark -caption \"Ark\" ", "/usr/share//icons/hicolor/16x16/apps/ark.png" },
     {"Artha", "artha", "/usr/share/pixmaps/artha.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Caribou", "caribou"},
     {"Disks", "gnome-disks", "/usr/share//icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Emacs", "emacs ", "/usr/share//icons/hicolor/16x16/apps/emacs.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"Filelight", "filelight ", "/usr/share//icons/hicolor/16x16/apps/filelight.png" },
     {"KCharSelect", "kcharselect -caption \"KCharSelect\"", "/usr/share//icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KWrite", "kwrite ", "/usr/share//icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share//icons/hicolor/16x16/apps/kate.png" },
     {"Keyboard", "matchbox-keyboard", "/usr/share/pixmaps/matchbox-keyboard.png" },
     {"Kvkbd", "kvkbd", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-keyboard.png" },
     {"Launchy", "launchy ", "/usr/share/pixmaps/launchy_icon.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Onboard", "onboard"},
     {"Onboard Settings", "onboard-settings"},
     {"PDF Editor", "pdfedit", "/usr/share/pixmaps/pdfedit.png" },
     {"Recoll", "recoll", "/usr/share//icons/hicolor/48x48/apps/recoll.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"SciTE Text Editor", "SciTE ", "/usr/share/pixmaps/Sci48M.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share//icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"Sensor Viewer", "xfce4-sensors", "/usr/share//icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Sweeper", "sweeper"},
     {"Thunar File Manager", "thunar ", "/usr/share//icons/hicolor/16x16/apps/Thunar.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"XTerm", "xterm"},
     {"pyRenamer", "/usr/bin/pyrenamer", "///usr/share/pyrenamer/pyrenamer.png" },
 }

xdgmenu = {    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Development", menu330f49df8243756a8a4dc7f7f7ee6dfe},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Lost & Found", menu1c1ecba6ad0b80ad52f0a2c15c785259},
    {"Multimedia", menu2f56b4f336dc97edf739bf79523fb9a6},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Settings", menuf4f70727dc34561dfde1a3c529b6205c},
    {"System", menua45da96d0bf6575970f2d27af22be28a},
    {"Utilities", menuceba282b7418b7f199798b645e1cba56},
}

