 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Jovie", "jovie"},
     {"KMag", "kmag -caption \"KMag\" ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouth", "kmouth -caption \"KMouth\" ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"Kvkbd", "kvkbd", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard.png" },
     {"Onboard", "onboard"},
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Akonaditray", "akonaditray"},
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/gnome/16x16/actions/gtk-find.png" },
     {"Ark", "ark -caption \"Ark\" ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Artha", "artha", "/usr/share/pixmaps/artha.png" },
     {"Disks", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Jovie", "jovie"},
     {"KCalc", "kcalc -caption \"KCalc\"", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KCharSelect", "kcharselect -caption \"KCharSelect\"", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KMag", "kmag -caption \"KMag\" ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouth", "kmouth -caption \"KMouth\" ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kvkbd", "kvkbd", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard.png" },
     {"LXTerminal", "lxterminal", "/usr/share/pixmaps/lxterminal.png" },
     {"Launchy", "launchy ", "/usr/share/pixmaps/launchy_icon.png" },
     {"Onboard", "onboard"},
     {"PDF Editor", "pdfedit", "/usr/share/pixmaps/pdfedit.png" },
     {"Recoll", "recoll", "/usr/share/icons/hicolor/48x48/apps/recoll.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Sweeper", "sweeper"},
     {"Synapse", "synapse"},
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"pyRenamer", "/usr/bin/pyrenamer", "///usr/share/pyrenamer/pyrenamer.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"MARY Component Installer", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/mary-component-installer", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY HTTP documentation", "", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY Uninstaller", "/usr/lib/jvm/java-7-openjdk/jre/bin/java -jar \"/home/prash/Documents/CoLi/Resources/MARY/Uninstaller/uninstaller.jar\"", "/usr/share/icons/gnome/16x16/status/trashcan_full.png" },
     {"MARY client", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/maryclient", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY server", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/maryserver", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"MARY web interface", "", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"Marble", "marble", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Mendeley Desktop", "/home/prash/.local/share/mendeleydesktop ", "/usr/share/icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Mendeley Desktop", "mendeleydesktop", "/usr/share/icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"Redstart", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/redstart", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
     {"Voice Import Tools", "xterm -e /home/prash/Documents/CoLi/Resources/MARY/bin/voiceimport", "///home/prash/Documents/CoLi/Resources/MARY/lib/icons/maryicon.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Counter-Strike Source", "steam steam://rungameid/240"},
     {"Portal (Beta)", "steam steam://rungameid/400"},
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Team Fortress 2", "steam steam://rungameid/440"},
     {"Team Fortress 2 Beta", "steam steam://rungameid/520", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"AcquireImages", "scangui  -caption AcquireImages ", "/usr/share/icons/gnome/16x16/devices/scanner.png" },
     {"Briss", "briss", "///usr/share/briss/briss-icon.png" },
     {"DNGConverter", "dngconverter  -caption DNGConverter ", "/usr/share/icons/hicolor/16x16/apps/dngconverter.png" },
     {"Darktable", "darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"ExpoBlending", "expoblending  -caption ExpoBlending ", "/usr/share/icons/hicolor/16x16/actions/expoblending.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MComix", "mcomix ", "/usr/share/icons/hicolor/16x16/apps/mcomix.png" },
     {"MuPDF", "mupdf ", "/usr/share/pixmaps/mupdf.xpm" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Panorama", "panoramagui  -caption Panorama ", "/usr/share/icons/hicolor/16x16/actions/panorama.png" },
     {"Photo Layouts Editor", "photolayoutseditor", "/usr/share/icons/hicolor/16x16/apps/photolayoutseditor.png" },
     {"RawTherapee", "rawtherapee ", "/usr/share/icons/hicolor/16x16/apps/rawtherapee.png" },
     {"Shotwell", "shotwell ", "/usr/share/icons/hicolor/16x16/apps/shotwell.svg" },
     {"UFRaw", "ufraw ", "/usr/share/pixmaps/ufraw.png" },
     {"digiKam", "digikam -caption digiKam ", "/usr/share/icons/hicolor/16x16/apps/digikam.png" },
     {"kgrapheditor", "kgrapheditor ", "/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"kgraphviewer", "kgraphviewer  -caption \"kgraphviewer\"", "/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"showFoto", "showfoto  -caption showFoto ", "/usr/share/icons/hicolor/16x16/apps/showfoto.png" },
     {"yEd Graph Editor", "yed ", "/usr/share/pixmaps/yed.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BlueDevil", "bluedevil-monolithic"},
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"GNUnet Secured P2P", "gnunet-fs-gtk", "/usr/share/icons/hicolor/16x16/apps/gnunet-fs-gtk.png" },
     {"GNUnet Setup", "gnunet-setup"},
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager", "/usr/share/icons/hicolor/16x16/apps/google-musicmanager.png" },
     {"KTorrent", "ktorrent ", "/usr/share/icons/hicolor/16x16/apps/ktorrent.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Midori", "midori ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Midori Private Browsing", "midori --private ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Opera", "/usr/bin/opera ", "/usr/share/icons/hicolor/16x16/apps/opera-browser.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"RSSOwl", "rssowl", "///usr/share/rssowl/icon.xpm" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Trojitá", "trojita", "/usr/share/icons/hicolor/32x32/apps/trojita.png" },
     {"Vidalia", "vidalia", "/usr/share/icons/hicolor/16x16/apps/vidalia.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/icons/hicolor/16x16/apps/wicd-gtk.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Kile", "kile ", "/usr/share/icons/hicolor/16x16/apps/kile.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"LyX Document Processor", "lyx ", "/usr/share/pixmaps/lyx.png" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Pybliographic Bibliography Manager", "pybliographic", "/usr/share/pixmaps/pybliographic.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"TeXworks", "texworks ", "/usr/share/pixmaps/TeXworks.png" },
     {"Trojitá", "trojita", "/usr/share/icons/hicolor/32x32/apps/trojita.png" },
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"Wordview Microsoft doc Viewer", "wordview", "/usr/share/pixmaps/wordview.xpm" },
     {"XMind", "/usr/share/xmind/XMind", "/usr/share/pixmaps/xmind.png" },
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.xpm" },
     {"llpp", "llpp "},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Code::Blocks IDE", "codeblocks ", "/usr/share/pixmaps/codeblocks.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/32x32/apps/eclipse.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Eric 5", "eric5", "/usr/share/pixmaps/eric.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"IPython2", "ipython2 qtconsole --pylab=qt", "///usr/lib/python2.7/site-packages/IPython/frontend/html/notebook/static/favicon.ico" },
     {"IPython3", "ipython qtconsole", "///usr/lib/python3.3/site-packages/IPython/frontend/html/notebook/static/favicon.ico" },
     {"KDiff3", "kdiff3  -caption \"KDiff3\"", "/usr/share/icons/hicolor/16x16/apps/kdiff3.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"PythonToolkit (PTK)", "PTK -f ", "/usr/share/pixmaps/ptkicon.svg" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Scala-IDE", "/usr/bin/eclipse", "///usr/share/eclipse/dropins/scala-ide/icon.png" },
     {"SciTE Text Editor", "SciTE ", "/usr/share/pixmaps/Sci48M.png" },
     {"Tortoise HG", "thg", "/usr/share/pixmaps/thg_logo.svg" },
     {"TortoiseHg", "thg --nofork", "/usr/share/pixmaps/thg_logo.svg" },
     {"Weka", "/usr/bin/weka", "/usr/share/pixmaps/weka.png" },
     {"Winpdb", "winpdb", "///usr/share/icons/winpdb-icon-16.png" },
     {"XDot", "python2 /home/shared/Source/xdot-git/xdot.py"},
     {"kdesvn", "kdesvn -caption \"kdesvn\"", "/usr/share/icons/hicolor/16x16/apps/kdesvn.png" },
     {"textadept", "textadept"},
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Weka", "/usr/bin/weka", "/usr/share/pixmaps/weka.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Audio Mixer", "xfce4-mixer", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Avidemux (GTK+)", "avidemux2_gtk", "/usr/share/pixmaps/avidemux.png" },
     {"Ex Falso", "exfalso", "/usr/share/icons/hicolor/64x64/apps/exfalso.png" },
     {"FFADO Mixer", "ffado-mixer"},
     {"GTK sound mixer", "/usr/bin/aumix", "///usr/share/aumix/aumix.xpm" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"Google Music Manager", "/opt/google/musicmanager/google-musicmanager", "/usr/share/icons/hicolor/16x16/apps/google-musicmanager.png" },
     {"Guitune", "gtkguitune"},
     {"HandBrake", "ghb", "/usr/share/icons/hicolor/16x16/apps/hb-icon.png" },
     {"Music Player", "lxmusic", "/usr/share/pixmaps/lxmusic.png" },
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"QjackCtl", "/usr/bin/qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"Qsynth", "/usr/bin/qsynth", "/usr/share/icons/hicolor/32x32/apps/qsynth.png" },
     {"Quod Libet", "quodlibet", "/usr/share/icons/hicolor/64x64/apps/quodlibet.png" },
     {"Rosegarden", "rosegarden ", "/usr/share/icons/hicolor/32x32/apps/rosegarden.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"Spotify", "spotify ", "/usr/local/share/icons/hicolor/16x16/apps/spotify-client.png" },
     {"VLC media player", "/usr/bin/vlc ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"soundKonverter", "soundkonverter ", "/usr/share/icons/hicolor/16x16/apps/soundkonverter.png" },
     {"tuxguitar", "tuxguitar  -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Dolphin", "dolphin  -caption \"Dolphin\" ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption \"KSystemLog\""},
     {"KUser", "xdg_menu_su kuser  -caption \"KUser\"", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Nepomuk File Indexing Controller", "nepomukcontroller"},
     {"PkgBrowser", "pkgbrowser", "/usr/share/icons/hicolor/48x48/apps/pkgbrowser.png" },
     {"Searchmonkey", "searchmonkey"},
     {"Sensor Viewer", "xfce4-sensors", "/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"Task Manager", "lxtask", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

